# Spring properties
#spring:
#  profiles:
#    active: cloud

---
spring:
  application:
     name: accounts-server
     #profiles: cloud

# HTTP Server
server:
  port: 55555   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

