# Spring properties
---
spring:
  application:
     name: accounts-server
     profiles: default

# HTTP Server
server:
  port: 55555   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

